jobify/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('static.urls')),
    path('user/', include('user.urls')),
    path('jobs/', include('test_results.urls')),
    path('jobinator/', include('jobinator.urls')),
    path('webscraper/', include('webscraper.urls')),
    path('alerts/', include('alerts.urls'))
]

test_results/urls.py
from django.urls import path

from . import views

app_name = 'jobs'
urlpatterns = [
    path('', views.index, name="index"),
    path('delete-all', views.delete_all, name="delete_all"),
    path('select-websites', views.select_websites, name="select_websites"),
    path('create-website', views.create_website, name="create_website"),
    path('update-website/<int:id>', views.update_website, name="update_website"),
    path('delete-website/<int:id>', views.delete_website, name="delete_website")
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('', views.profile, name='profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('register', views.register, name='register'),
]

test_results/forms.py
from django import forms
from webscraper.models import Website

class WebsiteForm(forms.ModelForm):
    class Meta:
        model = Website
        fields = '__all__'

test_results/views.py
from django.shortcuts import render, redirect
from webscraper.models import Job, Website
from django.core.paginator import Paginator
from .forms import WebsiteForm

# Create your views here.
def index(request):
    job_list = Job.objects.all().order_by('-created_at')

    paginator = Paginator(job_list, 10)
    page = request.GET.get('page', 1)

    jobs = paginator.page(page)

    context = {
        "jobs": jobs
    }

    return render(request, 'test_results/index.html', context)


def delete_all(request):
    jobs = Job.objects.all()
    for job in jobs:
        job.delete()

    return redirect('jobs:index')


def select_websites(request):
    websites = Website.objects.all().order_by('title')

    context = {
        "websites": websites
    }

    return render(request, 'test_results/select_websites.html', context)

def create_website(request):
    if request.method == 'POST':
        website_form = WebsiteForm(request.POST)
        if website_form.is_valid():
            title = website_form.cleaned_data["title"]
            url = website_form.cleaned_data["url"]
            query_prefix = website_form.cleaned_data["query_prefix"]
            position_query = website_form.cleaned_data["position_query"]
            location_query = website_form.cleaned_data["location_query"]
            postings_element = website_form.cleaned_data["postings_element"]
            postings_class_or_id = website_form.cleaned_data["postings_class_or_id"]
            posting_url_element = website_form.cleaned_data["posting_url_element"]
            posting_url_class_or_id = website_form.cleaned_data["posting_url_class_or_id"]
            posting_title_element = website_form.cleaned_data["posting_title_element"]
            posting_title_class_or_id = website_form.cleaned_data["posting_title_class_or_id"]
            posting_company_element = website_form.cleaned_data["posting_company_element"]
            posting_company_class_or_id = website_form.cleaned_data["posting_company_class_or_id"]
            posting_location_element = website_form.cleaned_data["posting_location_element"]
            posting_location_class_or_id = website_form.cleaned_data["posting_location_class_or_id"]
            Website.objects.create(
                title=title,
                url=url,
                query_prefix=query_prefix,
                position_query=position_query,
                location_query=location_query,
                postings_element=postings_element,
                postings_class_or_id=postings_class_or_id,
                posting_url_element=posting_url_element,
                posting_url_class_or_id=posting_url_class_or_id,
                posting_title_element=posting_title_element,
                posting_title_class_or_id=posting_title_class_or_id,
                posting_company_element=posting_company_element,
                posting_company_class_or_id=posting_company_class_or_id,
                posting_location_element=posting_location_element,
                posting_location_class_or_id=posting_location_class_or_id
            )
            return redirect('jobs:select_websites')
    else:
        website_form = WebsiteForm()

    context = {
        "website_form": website_form
    }

    return render(request, 'test_results/create_website.html', context)

def update_website(request, id):
    website = Website.objects.get(pk=id)

    if request.method == 'POST':
        website_form = WebsiteForm(request.POST, instance=website)
        if website_form.is_valid():
            website.save()
    else:
        website_form = WebsiteForm(instance=website)

    context = {
        "website": website,
        "website_form": website_form
    }

    return render(request, 'test_results/update_website.html', context)


def delete_website(request, id):
    website = Website.objects.get(pk=id)
    website.delete()

    return redirect('jobs:select_websites')

test_results/templates/test_results/create_website.html
{% extends 'base.html' %}

{% block content %}
<form class="form" action="{% url 'jobs:create_website' %}" method="post">
  {% csrf_token %}
  {{website_form.as_p}}
  <input type="submit" class="btn btn-primary" value="Create">
</form>
{% endblock %}

test_results/templates/test_results/index.html
{% extends "base.html" %}

{% block content %}
<center><a href="{% url 'jobs:delete_all' %}" class="btn btn-danger">Delete All</a></center>
<br>
{% for job in jobs %}
<div class="job-posting card" style="border: 1px solid #222; width: 80%; margin: 0 auto;">
  <div class="card-body">
    <div class="title card-title">
      <a href="{{job.url}}" target="_blank"><h5>{{job.title}}</h5></a>
    </div>
    <div class="job-info">
      <span class="company">{{job.company}}</span>
      <span>|</span>
      <span>{{job.location}}</span>
      <br>
      <span>{{job.salary}}</span>
      {% if job.salary and job.remote %}
      <span>|</span>
      {% endif %}
      <span>{{job.remote}}</span>
      <!--<p class="card-text">{{job.summary}}</p>-->
      <div class="job-meta">
        <small>Found at {{job.created_at}} on {{job.website_title}}</small>
      </div>
    </div>
  </div>
</div>
<hr>
{% endfor %}



{% if jobs.has_other_pages %}
<div class="pagination" style="width: 50%; margin: 0 auto; margin-bottom: 20px;">
  <ul class="pagination" style="width: 50%; margin: 0 auto;">
    {% if jobs.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ jobs.previous_page_number }}">Previous</a></li>
    {% else %}
    <li class="page-item disabled"><span class="page-link"></span></li>
    {% endif %}
    {% for i in jobs.paginator.page_range %}
    {% if jobs.number == i %}
    <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if jobs.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ jobs.next_page_number }}">Next</a></li>
    {% else %}
    <li class="page-item disabled"><span class="page-link"></span></li>
    {% endif %}
  </ul>
</div>
{% endif %}

{% endblock %}

test_results/templates/test_results/select_websites.html
{% extends 'base.html' %}

{% block content %}
<table class="table">
{% if websites %}
{% for website in websites %}
<tr>
  <td><a href="{% url 'jobs:update_website' website.id %}">{{website.title}}</a></td>
  <td><a href="{{ website.url }}">{{website.url}}</a></td>
  <td><a href="{% url 'jobs:delete_website' website.id %}" class="btn btn-danger">Delete</a></td>
</tr>
{% endfor %}
{% else %}
<p>You have no websites. <a href="{% url 'jobs:create_website' %}">Create one!</a></p>
{% endif %}
</table>
{% endblock %}

test_results/templates/test_results/update_website.html
{% extends 'base.html' %}

{% block content %}
<form class="form" action="{% url 'jobs:update_website' website.id %}" method="post">
  {% csrf_token %}
  {{website_form.as_p}}
  <input type="submit" class="btn btn-primary" value="Update">
</form>
{% endblock %}