alerts/urls.py
from django.urls import path

from . import views

app_name = 'alerts'
urlpatterns = [
    path('email-alerts', views.email_alerts, name="email_alerts"),
    path('new-user', views.new_user, name="new_user"),
    path('job-notifications', views.job_notification, name="job_notification"),
]

jobify/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('static.urls')),
    path('user/', include('user.urls')),
    path('jobs/', include('test_results.urls')),
    path('jobinator/', include('jobinator.urls')),
    path('webscraper/', include('webscraper.urls')),
    path('alerts/', include('alerts.urls'))
]

jobinator/urls.py
from django.urls import path

from . import views

app_name = 'jobinator'
urlpatterns = [
    path('my-jobs', views.my_jobs, name="my_jobs"),
    path('create-job', views.create, name="create_job"),
    path('activate-job/<int:id>', views.activate, name="activate_job"),
    path('deactivate-job/<int:id>', views.deactivate, name="deactivate_job"),
    path('delete-job/<int:id>', views.delete, name="delete_job"),
]

test_results/urls.py
from django.urls import path

from . import views

app_name = 'jobs'
urlpatterns = [
    path('', views.index, name="index"),
    path('delete-all', views.delete_all, name="delete_all"),
    path('select-websites', views.select_websites, name="select_websites"),
    path('create-website', views.create_website, name="create_website"),
    path('update-website/<int:id>', views.update_website, name="update_website"),
    path('delete-website/<int:id>', views.delete_website, name="delete_website")
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('', views.profile, name='profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('register', views.register, name='register'),
]

webscraper/urls.py
from django.urls import path

from . import views

app_name = 'webscraper'
urlpatterns = [
    path('', views.index, name="index")
]

templates/inc/navbar.html
<nav class="navbar navbar-expand navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'static:home' %}">Jobify</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'jobs:index' %}">Jobs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'jobinator:my_jobs' %}">Jobinator</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'webscraper:index' %}">Webscraper</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'alerts:email_alerts' %}">Alerts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user:profile' %}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user:login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user:register' %}">Register</a>
      </li>
      {% endif %}
  </div>
</nav>