jobify/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('static.urls')),
    path('user/', include('user.urls')),
    path('jobs/', include('test_results.urls')),
    path('jobinator/', include('jobinator.urls')),
    path('webscraper/', include('webscraper.urls')),
    path('alerts/', include('alerts.urls'))
]

jobinator/urls.py
from django.urls import path

from . import views

app_name = 'jobinator'
urlpatterns = [
    path('my-jobs', views.my_jobs, name="my_jobs"),
    path('create-job', views.create, name="create_job"),
    path('activate-job/<int:id>', views.activate, name="activate_job"),
    path('deactivate-job/<int:id>', views.deactivate, name="deactivate_job"),
    path('delete-job/<int:id>', views.delete, name="delete_job"),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('', views.profile, name='profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('register', views.register, name='register'),
]

jobinator/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Jobinator(models.Model):
    position = models.CharField(max_length=250)
    location = models.CharField(max_length=250)
    active   = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.position

    class Meta:
        ordering = ['created_at']

    class Admin:
        pass

jobinator/forms.py
from django import forms

class JobinatorForm(forms.Form):
    position = forms.CharField(label='Position', max_length=100)
    location = forms.CharField(label='Location', max_length=100)

jobinator/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import JobinatorForm
from .models import Jobinator

# Create your views here.
def my_jobs(request):
    jobs = Jobinator.objects.all()

    context = {
        'jobs': jobs
    }
    return render(request, 'jobinator/my_jobs.html', context)


def create(request):
    if request.method == 'POST':
        form = JobinatorForm(request.POST)
        if form.is_valid():
            position = form.cleaned_data['position']
            location = form.cleaned_data['location']
            Jobinator.objects.create(
                position=position,
                location=location
            )
            return HttpResponseRedirect('/jobinator/my-jobs')
    else:
        form = JobinatorForm()

    context = {
        'form': form
    }
    return render(request, 'jobinator/create_job.html', context)


def activate(request, id):
    current_active = Jobinator.objects.filter(active=True)
    for job in current_active:
        job.active = False
        job.save()

    new_active = Jobinator.objects.get(pk=id)
    new_active.active = True
    new_active.save()

    return HttpResponseRedirect('/jobinator/my-jobs')


def deactivate(request, id):
    current_active = Jobinator.objects.get(pk=id)
    current_active.active = False
    current_active.save()

    return HttpResponseRedirect('/jobinator/my-jobs')


def delete(request, id):
    job_to_be_deleted = Jobinator.objects.get(pk=id)
    job_to_be_deleted.delete()

    return HttpResponseRedirect('/jobinator/my-jobs')

jobinator/templates/jobinator/create_job.html
{% extends "base.html" %}

{% block content %}
<h3>Jobinator</h3>
<p>Register your interest in a position and receive notifications of new postings.</p>
<br>
<form class="form" action="{% url 'jobinator:create_job' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit" class="btn btn-success">
</form>
{% endblock %}

jobinator/templates/jobinator/index.html
{% extends "base.html" %}

{% block content %}
<h3>Jobinator</h3>
<p>Register your interest in a position and receive notifications of new postings.</p>
<br>
<form class="form" action="/jobinator/" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit" class="btn btn-success">
</form>
{% endblock %}

jobinator/templates/jobinator/my_jobs.html
{% extends "base.html" %}

{% block content %}
<h1 class="d-inline">Your saved job alerts</h1>
<a href="{% url 'jobinator:create_job' %}" class="btn btn-success d-inline">Create alert</a>
<br>
<br>
{% if jobs %}
{% for job in jobs %}
<div class="card" style="width: 30%">
  <span class="d-inline">Position: {{job.position}}</span>
  <span class="d-inline">Location: {{job.location}}</span>
  <span class="d-inline">Active: {{job.active}}</span>
  {% if job.active == False %}
  <a href="{% url 'jobinator:activate_job' job.id %}" class="btn btn-success d-inline"
  style="width: 50%">Activate</a>
  {% else %}
  <a href="{% url 'jobinator:deactivate_job' job.id %}" class="btn btn-success d-inline"
  style="width: 50%">Deactivate</a>
  {% endif %}
  <a href="{% url 'jobinator:delete_job' job.id %}" class="btn btn-danger d-inline"
  style="width: 50%">Delete</a>
</div>
{% endfor %}
{% else %}
<p>You have no saved job alerts. <a href="{% url 'jobinator:create_job' %}">Create one!</a></p>
{% endif %}
{% endblock %}